package org.sang.model;

public class Bulletin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bulletin.id
     *
     * @mbg.generated Sun Dec 12 11:14:13 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bulletin.message
     *
     * @mbg.generated Sun Dec 12 11:14:13 CST 2021
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bulletin.id
     *
     * @return the value of bulletin.id
     *
     * @mbg.generated Sun Dec 12 11:14:13 CST 2021
     */


    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bulletin.id
     *
     * @param id the value for bulletin.id
     *
     * @mbg.generated Sun Dec 12 11:14:13 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bulletin.message
     *
     * @return the value of bulletin.message
     *
     * @mbg.generated Sun Dec 12 11:14:13 CST 2021
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bulletin.message
     *
     * @param message the value for bulletin.message
     *
     * @mbg.generated Sun Dec 12 11:14:13 CST 2021
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

}