package org.sang.model;

public class UserAndBulletin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ub.id
     *
     * @mbg.generated Sun Dec 12 11:14:13 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ub.userid
     *
     * @mbg.generated Sun Dec 12 11:14:13 CST 2021
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ub.bid
     *
     * @mbg.generated Sun Dec 12 11:14:13 CST 2021
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ub.state
     *
     * @mbg.generated Sun Dec 12 11:14:13 CST 2021
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ub.id
     *
     * @return the value of ub.id
     *
     * @mbg.generated Sun Dec 12 11:14:13 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ub.id
     *
     * @param id the value for ub.id
     *
     * @mbg.generated Sun Dec 12 11:14:13 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ub.userid
     *
     * @return the value of ub.userid
     *
     * @mbg.generated Sun Dec 12 11:14:13 CST 2021
     */
    public Integer getUserid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ub.userid
     *
     * @param uid the value for ub.userid
     *
     * @mbg.generated Sun Dec 12 11:14:13 CST 2021
     */
    public void setUserid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ub.bid
     *
     * @return the value of ub.bid
     *
     * @mbg.generated Sun Dec 12 11:14:13 CST 2021
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ub.bid
     *
     * @param bid the value for ub.bid
     *
     * @mbg.generated Sun Dec 12 11:14:13 CST 2021
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ub.state
     *
     * @return the value of ub.state
     *
     * @mbg.generated Sun Dec 12 11:14:13 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ub.state
     *
     * @param state the value for ub.state
     *
     * @mbg.generated Sun Dec 12 11:14:13 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }
}