spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
    type: com.alibaba.druid.pool.DruidDataSource